apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nge-example-server
  name: nge-example-server
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: nge-example-server
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nge-example-server
        spring-metrics: enabled
    spec:
      containers:
      - image: ###IMAGE### 
        imagePullPolicy: Always
        env:
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:postgresql://nrp-app:5432/sampleapp"
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: postgres.nrp-app.credentials
              key: username
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres.nrp-app.credentials
              key: password
        - name: SPRING_JPA_HIBERNATE_DDL_AUTO
          value: "none"
        ports:
        - containerPort: 8080
          name: http
        name: nge-example-server
      imagePullSecrets:
      - name: ###PULLSECRET###
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nge-example-server
    spring-metrics: enabled
  name: nge-example-server
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    name: http
  selector:
    app: nge-example-server
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nge-example-server
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  rules:
    - host: "backend.nge.altemista.cloud"
      http:
        paths:
        - path: /
          backend:
            serviceName: nge-example-server 
            servicePort: 8080
  tls:
    - hosts:
        - backend.nge.altemista.cloud
      secretName: tls-backend
---

# role required for monitoring to collect metrics

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: prometheus-k8s
  namespace: nge-example-server
rules:
- apiGroups:
  - ""
  resources:
  - services
  - endpoints
  - pods
  verbs:
  - get
  - list
  - watch

---

# rolebinding to attach the role to the serviceaccount in the monitoring namespace

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prometheus-k8s
  namespace: nge-example-server
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: prometheus-k8s
subjects:
- kind: ServiceAccount
  name: prometheus-k8s
  namespace: monitoring

---

# servicemonitor: entity to tell the prometheus operator to scrape a certain target

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: spring-metrics
spec:
  endpoints:
  - path: /actuator/prometheus
    port: http
  jobLabel: spring_metrics
  selector:
    matchLabels:
      spring-metrics: enabled
---

apiVersion: acid.zalan.do/v1
kind: postgresql
metadata:
  name: nrp-app
spec:
  databases:
    sampleapp: sample
  numberOfInstances: 2
  patroni:
    pg_hba:
    - host all all 0.0.0.0/0 md5
  postgresql:
    version: "9.6"
  teamId: nrp
  users:
    sample:
    - login
    root:
    - superuser
    - createdb
  volume:
    size: 2Gi
  sidecars:
    - name: "exporter"
      image: "wrouesnel/postgres_exporter:v0.8.0"
      ports:
        - name: exporter
          containerPort: 9187
          protocol: TCP
      resources:
        limits:
          cpu: 100m
          memory: 128M
        requests:
          cpu: 100m
          memory: 128M
      env:
        - name: "DATA_SOURCE_URI"
          value: "nrp-app/sampleapp?sslmode=disable"
        - name: "DATA_SOURCE_USER"
          valueFrom:
            secretKeyRef:
              name: postgres.nrp-app.credentials
              key: username
        - name: "DATA_SOURCE_PASS"
          valueFrom:
            secretKeyRef:
              name: postgres.nrp-app.credentials
              key: password

---
apiVersion: v1
kind: Service
metadata:
  name: pg-exporter
  labels:
    app: pg-exporter
spec:
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
    - name: exporter
      port: 9187
      targetPort: exporter
  selector:
    application: spilo
    team: nrp

---
# servicemonitor: entity to tell the prometheus operator to scrape a certain target

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: postgres-metrics
spec:
  endpoints:
  - path: /metrics
    port: exporter
  jobLabel: postgres_metrics
  selector:
    matchLabels:
      app: pg-exporter
